# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('termsandconditions', '0003_auto_20170627_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='date_accepted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Accepted'),
        ),
    ]
